apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap
  namespace: werify-staging
data:
  ASAAS_BASE_URL: "https://sandbox.asaas.com/"
  DISABLE_REGISTRATION: "false"
  MIX_ENV: "prod"
  OPENAI_BASE_URL: "https://api.openai.com/v1"
  OPENAI_TRANSCRIPTION_MODEL: "whisper-1"
  PHX_HOST: "staging.werify.app"
  SMTP_PORT: "587"
  SMTP_RELAY: "smtp.resend.com"
  SMTP_USERNAME: "resend"
  TRANSCRIPTION_ADAPTER: "openai"
