apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - configmap.yaml
  - external-secret.yaml
  - ghcr-external-secret.yaml
  - deployment.yaml
  - ingress.yaml
