apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: werify
  namespace: werify
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-buffering: "off"
    nginx.ingress.kubernetes.io/websocket-services: "werify"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  rules:
  - host: werify.app
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: werify
            port:
              number: 4000
  - host: staging.werify.app
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: werify
            port:
              number: 4000
