apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bugsink
  namespace: bugsink
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-dns
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - bugsink.internal.prakash.com.br
      secretName: bugsink-tls
  rules:
    - host: bugsink.internal.prakash.com.br
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: bugsink
                port:
                  number: 8000
