apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - local-path-static.yaml
  - werify-staging-uploads-pv.yaml
  - werify-production-uploads-pv.yaml
  - bugsink-data-pv.yaml
