apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - pvc.yaml
  - external-secret.yaml
  - datasources.yaml
  - dashboard-provisioning.yaml
  - deployment.yaml
  - ingress.yaml

# Generate ConfigMap from dashboard JSON files
configMapGenerator:
  - name: grafana-dashboards
    namespace: grafana
    files:
      - dashboards/k8s-overview.json
      - dashboards/werify.json
    options:
      disableNameSuffixHash: true
