apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - pvc.yaml
  # NOTE: secret.yaml is created manually (encrypted version stored as secret.yaml.gpg)
  # Run: gpg -d grafana/secret.yaml.gpg | kubectl apply -f -
  - datasources.yaml
  - dashboard-provisioning.yaml
  - deployment.yaml
  - ingress.yaml

# Generate ConfigMap from dashboard JSON files
configMapGenerator:
  - name: grafana-dashboards
    namespace: grafana
    files:
      - dashboards/k8s-overview.json
      - dashboards/werify.json
    options:
      disableNameSuffixHash: true
